import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import { VitePWA } from "vite-plugin-pwa";

// SPA mode only — no TanStack Start SSR, since the build target is a Node-free
// Docker image where FastAPI serves static files (spec Section 4).
export default defineConfig({
  plugins: [
    tanstackRouter({ target: "react", autoCodeSplitting: true }),
    react(),
    VitePWA({
      registerType: "autoUpdate",
      // globPatterns below already precaches every PNG in public/; leaving
      // this on would add the manifest icons a second time.
      includeManifestIcons: false,
      workbox: {
        // Offline queue (spec Section 4): captured stops/photos are written to
        // IndexedDB by src/offline/ and synced when connectivity returns. The
        // service worker here only handles asset caching for installability —
        // the queue itself is app-level logic, not a Workbox strategy.
        globPatterns: ["**/*.{js,css,html,svg,png,ico}"],
        // Cold open of any deep link (/t/$slug...) offline renders the
        // precached shell. /api is denylisted so API calls always hit the
        // network — no runtimeCaching for the API. There is no persisted Query
        // cache (decision-log Entry 19): the only offline read is the trip
        // record, kept in localStorage by src/localStore.ts / src/trip.ts.
        navigateFallback: "index.html",
        navigateFallbackDenylist: [/^\/api\//],
      },
      manifest: {
        name: "Bike Trip Journal",
        short_name: "Bike Trip",
        display: "standalone",
        start_url: "/",
        // Matches the icons' BG in scripts/generate-icons.py (31, 92, 64).
        theme_color: "#1f5c40",
        background_color: "#1f5c40",
        // Chrome's install criteria need 192 and 512 PNGs. Generated by
        // scripts/generate-icons.py into public/ (copied to the dist root).
        icons: [
          { src: "/pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "/pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "/pwa-maskable-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      // Local dev: Vite dev server proxies /api to the FastAPI container so
      // there's no CORS config to maintain (matches prod, where the same
      // container serves both).
      "/api": "http://localhost:8000",
    },
  },
});
