import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// routeTree.gen.ts is generated by @tanstack/router-plugin from src/routes/
// at dev/build time — not committed, see .gitignore.
import { routeTree } from "./routeTree.gen";
import { startQueue } from "./offline/queue";

const queryClient = new QueryClient();
startQueue(queryClient);
const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
