// The root route mounts the real QueueNotice, which reads the queue's IndexedDB.
import "fake-indexeddb/auto";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createMemoryHistory, createRouter } from "@tanstack/react-router";
// Generated by the router plugin during `npm run build`, which the validation
// command runs before `npm test`.
import { routeTree } from "./routeTree.gen";
import { parseTripLink } from "./trip";
import type { TripOut } from "./api/gen/types/TripOut";

// t-frontend-slug-routing: `/` → last trip or paste screen, and the /t/$slug
// shell's pending / cached / not-found / unreachable states (decision-log
// Entries 18 and 19). Driven through the real route tree and generated client,
// with only globalThis.fetch mocked.

const fetchMock = vi.fn<typeof fetch>();

const TRIP: TripOut = { id: "t1", name: "Stuart Hwy 2026", startDate: "2026-10-01", bikes: [], access: "rider", visibility: "private", publicDelayHours: 24, riderCount: 1, lastPublicStopAt: null, viewer: { role: "rider" } };
const CACHED: TripOut = { ...TRIP, name: "Cached name" };

const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
const envelope = (code: string) => ({ error: { code, message: code.toLowerCase() } });
const networkDown = () => Promise.reject(new TypeError("Failed to fetch"));

/** No retries by default, so an unreachable server fails immediately. */
const noRetry = () => new QueryClient({ defaultOptions: { queries: { retry: false } } });
/** Retries on (TanStack's default count), without the backoff wait. */
const retryOn = () => new QueryClient({ defaultOptions: { queries: { retry: 3, retryDelay: 0 } } });

function renderAt(path: string, queryClient: QueryClient = noRetry()) {
  const router = createRouter({ routeTree, history: createMemoryHistory({ initialEntries: [path] }) });
  render(
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>,
  );
  return router;
}

const stored = (key: string) => localStorage.getItem(key);
const settle = () => act(() => new Promise((r) => setTimeout(r, 20)));

beforeEach(() => {
  localStorage.clear();
  fetchMock.mockReset();
  // The trip home also requests GET /api/trips/{slug}/map and /stops; answer them empty
  // so fetchMock (and its call counts) sees trip requests only.
  vi.stubGlobal("fetch", (input: RequestInfo | URL, init?: RequestInit) =>
    String(input).endsWith("/map")
      ? Promise.resolve(json(200, { type: "FeatureCollection", features: [] }))
      : String(input).endsWith("/stops")
        ? Promise.resolve(json(200, []))
        : fetchMock(input, init),
  );
  vi.stubGlobal("scrollTo", () => {}); // jsdom lacks it; the router calls it on navigation
});
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("AC1: / redirect", () => {
  test("with btj.lastSlug, / replaces itself with /t/<slug>", async () => {
    localStorage.setItem("btj.lastSlug", "abc");
    fetchMock.mockImplementation(async () => json(200, TRIP));
    const router = renderAt("/");
    await waitFor(() => expect(router.state.location.pathname).toBe("/t/abc"));
    expect(router.history.length).toBe(1); // replace, not push
    expect(await screen.findByRole("heading", { name: TRIP.name })).toBeTruthy();
  });

  test("without btj.lastSlug, / shows the paste screen and fetches nothing", async () => {
    const router = renderAt("/");
    expect(await screen.findByLabelText("Paste your trip link")).toBeTruthy();
    expect(router.state.location.pathname).toBe("/");
    expect(fetchMock).not.toHaveBeenCalled();
  });
});

describe("AC2: parseTripLink", () => {
  test.each([
    ["https://x.app/t/abc", "abc"],
    ["https://x.app/t/abc/stops/9", "abc"],
    ["  abc  ", "abc"],
    ["", null],
    ["https://x.app/foo", null],
    ["a/b", null],
    ["   ", null],
  ])("%j → %j", (input, expected) => {
    expect(parseTripLink(input)).toBe(expected);
  });
});

describe("AC3: paste screen", () => {
  async function submit(value: string) {
    const input = await screen.findByLabelText("Paste your trip link");
    fireEvent.change(input, { target: { value } });
    fireEvent.click(screen.getByRole("button", { name: "Open trip" }));
  }

  test("a valid link navigates to /t/<slug>", async () => {
    fetchMock.mockImplementation(async () => json(200, TRIP));
    const router = renderAt("/");
    await submit("https://x.app/t/abc/stops/9");
    await waitFor(() => expect(router.state.location.pathname).toBe("/t/abc"));
  });

  test("an invalid link shows an inline message and stays on /", async () => {
    const router = renderAt("/");
    await submit("https://x.app/foo");
    expect((await screen.findByRole("alert")).textContent).toBe("That doesn't look like a trip link.");
    await settle();
    expect(router.state.location.pathname).toBe("/");
    expect(fetchMock).not.toHaveBeenCalled();
  });
});

test("AC4: pending with no cached trip shows the wake-up message", async () => {
  fetchMock.mockImplementation(() => new Promise<Response>(() => {}));
  renderAt("/t/abc");
  expect(await screen.findByText("Waking up the server…")).toBeTruthy();
});

describe("AC5: success", () => {
  test.each(["rider", "viewer"] as const)("%s slug: name renders, trip cached, lastSlug set", async (access) => {
    const trip = { ...TRIP, access };
    fetchMock.mockImplementation(async () => json(200, trip));
    renderAt("/t/abc");
    expect(await screen.findByRole("heading", { name: TRIP.name })).toBeTruthy();
    await waitFor(() => expect(stored("btj.lastSlug")).toBe("abc"));
    expect(JSON.parse(stored("btj.trip.abc")!)).toEqual(trip);
    expect(fetchMock.mock.calls[0][0]).toBe("/api/trips/abc");
  });

  test("a fresh response replaces a stale cached trip", async () => {
    localStorage.setItem("btj.trip.abc", JSON.stringify(CACHED));
    fetchMock.mockImplementation(async () => json(200, TRIP));
    renderAt("/t/abc");
    expect(await screen.findByRole("heading", { name: TRIP.name })).toBeTruthy();
    await waitFor(() => expect(JSON.parse(stored("btj.trip.abc")!)).toEqual(TRIP));
  });
});

describe("AC6: cached trip survives an unreachable server", () => {
  test.each([
    ["network failure", networkDown],
    ["502 without envelope", async () => new Response("<html>bad gateway</html>", { status: 502 })],
  ])("%s: cached name renders, no error screen, cache untouched", async (_, impl) => {
    localStorage.setItem("btj.trip.abc", JSON.stringify(CACHED));
    fetchMock.mockImplementation(impl);
    renderAt("/t/abc");
    expect(await screen.findByRole("heading", { name: CACHED.name })).toBeTruthy();
    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    await settle();
    expect(screen.getByRole("heading", { name: CACHED.name })).toBeTruthy();
    expect(screen.queryByText("Can't reach the server")).toBeNull();
    expect(JSON.parse(stored("btj.trip.abc")!)).toEqual(CACHED);
    // Rendering the cached copy is not a successful open: lastSlug is not written.
    expect(stored("btj.lastSlug")).toBeNull();
  });
});

describe("AC7: NOT_FOUND envelope", () => {
  test("overrides the cache, clears it and a matching lastSlug, never retries", async () => {
    localStorage.setItem("btj.trip.abc", JSON.stringify(CACHED));
    localStorage.setItem("btj.lastSlug", "abc");
    fetchMock.mockImplementation(async () => json(404, envelope("NOT_FOUND")));
    renderAt("/t/abc", retryOn());
    expect(await screen.findByText("Trip not found")).toBeTruthy();
    expect(screen.queryByRole("heading", { name: CACHED.name })).toBeNull();
    await waitFor(() => expect(stored("btj.trip.abc")).toBeNull());
    expect(stored("btj.lastSlug")).toBeNull();
    await settle();
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });

  test("leaves lastSlug alone when it points at a different trip", async () => {
    localStorage.setItem("btj.lastSlug", "other");
    localStorage.setItem("btj.trip.other", JSON.stringify(TRIP));
    fetchMock.mockImplementation(async () => json(404, envelope("NOT_FOUND")));
    renderAt("/t/abc");
    expect(await screen.findByText("Trip not found")).toBeTruthy();
    await settle();
    expect(stored("btj.lastSlug")).toBe("other");
    expect(stored("btj.trip.other")).not.toBeNull();
  });

  test("a 404 without an envelope is unreachable, not not-found", async () => {
    localStorage.setItem("btj.lastSlug", "abc");
    fetchMock.mockImplementation(async () => new Response("Not Found", { status: 404 }));
    renderAt("/t/abc");
    expect(await screen.findByText("Can't reach the server")).toBeTruthy();
    expect(screen.queryByText("Trip not found")).toBeNull();
    expect(stored("btj.lastSlug")).toBe("abc");
  });
});

describe("AC8: no cache and unreachable", () => {
  test.each([
    ["network failure", networkDown],
    ["502 without envelope", async () => new Response("<html>bad gateway</html>", { status: 502 })],
    ["INTERNAL_ERROR envelope", async () => json(500, envelope("INTERNAL_ERROR"))],
  ])("%s: error screen, Retry refetches and recovers", async (_, impl) => {
    fetchMock.mockImplementationOnce(impl);
    renderAt("/t/abc");
    expect(await screen.findByText("Can't reach the server")).toBeTruthy();
    expect(fetchMock).toHaveBeenCalledTimes(1);

    fetchMock.mockImplementationOnce(async () => json(200, TRIP));
    fireEvent.click(screen.getByRole("button", { name: "Retry" }));
    expect(await screen.findByRole("heading", { name: TRIP.name })).toBeTruthy();
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });

  test("with retries on, an unenveloped failure is retried before the error screen", async () => {
    fetchMock.mockImplementation(networkDown);
    renderAt("/t/abc", retryOn());
    expect(await screen.findByText("Can't reach the server")).toBeTruthy();
    expect(fetchMock).toHaveBeenCalledTimes(4);
  });

  test("with retries on, an INTERNAL_ERROR envelope is not retried", async () => {
    fetchMock.mockImplementation(async () => json(500, envelope("INTERNAL_ERROR")));
    renderAt("/t/abc", retryOn());
    expect(await screen.findByText("Can't reach the server")).toBeTruthy();
    await settle();
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});
